### ISSUE TITLE
Should allow setting brightness/color of light when it turns on

### ISSUE THREAD

**Issue by johnhans** [mark-bloom/OctoLight_Home-Assistant#10]
Great concept, but could be even better if it allowed to set the brightness/color of the light it turns on as well. If the light is dimmed, it is still dimmed when turned on, since HA remembers the last state of the light. Alternately, OctoLight could allow calling a Scene, which may be easier to implement?

**Comment by mark-bloom** [comment]
Noted - I haven't tested the impact of including those settings when using a 'switch object' as opposed to a 'light object' in HA. I may create a 'light object' specific branch to test out these features, but I have no plans to implement this in the main branch currently..

**Comment by mark-bloom** [comment]
Not planned for current timelines.

**Comment by mark-bloom** [comment]
Not planned for current timelines.
