### ISSUE TITLE
Support multiple lights/switches

### ISSUE THREAD

**Issue by Steeven9** [mark-bloom/OctoLight_Home-Assistant#11]
**Is your feature request related to a problem? Please describe.**
I'm using this plugin to turn on and off the printer light, but it would also be cool to manage the room light (which uses a smart switch).

**Describe the solution you'd like**
I'd like to have the possibility of turning on and off multiple lights/switches separately, each with the same options as now (turn off after print, etc.).

**Describe alternatives you've considered**
I thought about installing the plugin twice with different settings but I'm not sure that would work...

**Additional context**
-

**Comment by mark-bloom** [comment]
I've opened another branch and am locally testing the feature, but duplicating all those settings is introducing problems to the core program. Multiple lights/switches together should be fine to be controlled together (if the entity in settings refers to a group), but seperate control is not planned, based on current testing.
