### ISSUE TITLE
Changing the bulb icon to a power icon.

### ISSUE THREAD

**Issue by Efekent** [mark-bloom/OctoLight_Home-Assistant#12]
Hello @mark-bloom,
First, thanks for this nice plugin, it works nice!
I have a question, it also might be seen as future request.

**Is your feature request related to a problem? Please describe.**
There is no issue, but I like to have possibility to change the bulb icon to power icon.
The reason is that I have been using a different plugin which turns on the lights through GPIO pins with relay boards for years, I have tried to power off and on the printer through the same system but after a couple of months the relays stick and won't power off anymore. So I was using a Zigbee Plug through Home Assistant.

Then I came across OctoLight_Home-Assistant last week, I thought hallelujah!, finally a way to do this through OctoPi, but the icon I have for the GPIO version is exactly the same icon as the OctoLight_Home-Assistant icon.
And if you know how I am, you could guess that I am dumb enough to turn off the Zigbee socket instead of the lights in the middle of a large print going on.

**Describe the solution you'd like**
I would love to see a way to choose your own icon or a pre added power icon for users can choose between light or power icon.

**Describe alternatives you've considered**
Alternative would be a way to change the icon myself in the script or replace the bulb icon, if someone can show me how to that I will happy too. I have no idea where to start.

Thanks in advance!

**Comment by Efekent** [comment]
My apologies @mark-bloom I didn't look hard enough I guess, I got it working.

Most right icon, not quite power icon, but this looked like close enough:
![power_icon](https://github.com/user-attachments/assets/3cf10b8b-d358-4e71-b4d8-2b6801fdc8a6)

Found octolightHA_navbar.jinja2 and replaced 1F4A1 with 26A1

Funny thing is, I got two instances and on one if I turn on the power plug, bulb icon gets yellow instead of the lightning icon and on the other works other way around, but I will look into that. 

Thanks for the plugin again, if you want to close this it is fine, or maybe you want to add it in future update.
I don't mind changing the icon after every update of this plugin.

**Comment by mark-bloom** [comment]
Thanks @Efekent for identifying the line for changing the icon. I'm unlikely to change the plugin itself, but I'll look into the icon changing process (including the wrong icon going yellow) and add it to the readme instructions for those that want to do it.

**Comment by Efekent** [comment]
Thank you @mark-bloom, the potential to use your plugin for something else than only light is great, I have ZHA with 117 devices, I can even use it to activate something else around the house or even make an automation script when the print finishes take a snapshot from the printer cam and mail it to my email, possibilities are endless with HA. 

It would be great if we could manage more entities with it.
