### ISSUE TITLE
Light triggered in mulitple scenarios when used together with Octopod app

### ISSUE THREAD

**Issue by levelsw** [mark-bloom/OctoLight_Home-Assistant#13]
When using this plugin together with using the Octopod app for iPhone, the switch is turned on in the following scenarios:
- opening the app
- switching to the control page
- switching to the panel page

1. Open the Octopod app

The switch not to be turned on during these actions (no triggers have been enabled in the settings for turning on the switch during certain events)

Screenshots don't really show anything. I can create a video if that helps

**Your software and hardware (please complete the following information):**
 - OctoPrint or OctoPi version: 1.10.2
 - Browser: N/A, Octopod app in iOS
 - Plugin version 0.0.4

**Additional context**
No issues directly in Octoprint, I'm not able to trigger the same sort of behavior when switching pages

**Comment by mark-bloom** [comment]
I have no iOS devices available to install Octopod debug this issue. If you are able to extract any logs from Octopod to further identify the issue, that may help, otherwise there is nothing I can do to resolve this issue, outside input would be required.
