### ISSUE TITLE
Invalid URL in setup.py

### ISSUE THREAD

**Issue by gdombiak** [mark-bloom/OctoLight_Home-Assistant#2]
The URL [in this file](https://github.com/mark-bloom/OctoLight_Home-Assistant/blob/535cdb8682b3817cae6c486d70ac8bf70b216ef2/setup.py#L30) should point to 'https://github.com/mark-bloom/OctoLight_Home-Assistant'

**Comment by mark-bloom** [comment]
Thank you, corrected the incorrect URL and uploaded as v0.0.2 to the plugin repository (working on personal setup but please advise if any further issues)
