### ISSUE TITLE
After installing the plugin is not displayed as installed nor available to configure

### ISSUE THREAD

**Issue by pvmil** [mark-bloom/OctoLight_Home-Assistant#8]
**Describe the bug**
After installing the plugin is not displayed as installed nor available to configure

**To Reproduce**
Install 

**Expected behavior**
Plugin visibility in list of installed plugins and in the list of plugins which can be configured

**Your software and hardware (please complete the following information):**
 - OctoPrint 1.9.2 / OctoPi version:1.0.0
 - Edge
 - Plugin version : I only see one release on github, so I expect 'Initial' but I cannot see that in octoprint now

Can I help in debugging this? Can I find additional logging or somehow reinstall?

(I would really like to have this plugin active for easy switching the light, thanks for your effort)

**Comment by pvmil** [comment]
Ah, (sorry for being a new Octoprint user). I see the plugin is disabled, And I can see the version is 0.0.1 now.
When I enable it no configuration panel is shown, when I restart octoprint afterwards it is again disabled

**Comment by venator42** [comment]
Already mentioned in #6. It is a syntax error

**Comment by pvmil** [comment]
Ok, so duplicate, I'll close this one

**Comment by pvmil** [comment]
Thanks for fixing this, great job

**Comment by mark-bloom** [comment]
Not a problem. Didn't realise GitHub didn't have me watching my own repository, so only realised there were issues to fix after 3 weeks.
